apiVersion: v1
kind: Pod
metadata:
  name: my-busybox
  labels:
    name: my-busybox
  namespace: dev2406
spec:
  containers:
    - name: secret
      image: busybox
      command: ['/bin/sh', '-c', 'sleep 3600']
      volumeMounts:
        - mountPath: /etc/secret-volume
          name: secret-volume
  volumes:
    - name: secret-volume
      secret:
        secretName: dotfile-secret
  nodeSelector:
    name: controlplane
