apiVersion: v1
kind: Pod
metadata:
  labels:
    app: gop-file-server
  name: gop-file-server
spec:
  containers:
  - image: kodekloud/fileserver
    name: fileserver
    volumeMounts:
    - mountPath: /web
      name: data-store
  volumes:
  - name: data-store
    persistentVolumeClaim:
      claimName: data-pvc
