apiVersion: v1
kind: Pod
metadata:
  namespace: dvl1987
  name: time-check
  labels:
    run: time-check
spec:
  containers:
  - name: busybox
    image: busybox
    env:
    - name: TIME_FREQ
      valueFrom:
        configMapKeyRef:
          name: time-config
          key: TIME_FREQ
    command:
    - "/bin/sh"
    - "-c"
    - "while true; do date; sleep $TIME_FREQ;done > /opt/time/time-check.log"
    volumeMounts:
      - mountPath: /opt/time
        name: log-volume
  volumes:
  - name: log-volume
    emptyDir: {}
