apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    name: nginx-deploy
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  selector:
    matchLabels:
      name: nginx-deploy
  template:
    metadata:
      name: nginx-deploy
      labels:
        name: nginx-deploy
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
