apiVersion: v1
kind: Pod
metadata:
  name: logger
  labels:
    name: logger
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      volumeMounts:
        - mountPath: /var/www/nginx
          name: log-volume
  volumes:
    - name: log-volume
      persistentVolumeClaim:
        claimName: log-claim
